<?php
/**
 * Test class for CWebSource.
 * Generated by PHPUnit on 2011-02-01 at 21:37:40.
 */
class CWebSourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CWebSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CWebSource;
    }
    
    
    public function testWebSourceIsNull(){
        $this->assertNull($this->object->url);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
