<?php
/**
 * Test class for CWebSource.
 * Generated by PHPUnit on 2011-02-01 at 21:37:40.
 */
class CCSSLocatorTest extends PHPUnit_Framework_TestCase {
     private $testSelector = '#div1 a';
    /**
     * @var CCSSLocator
     */
    protected $object;
    

    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testExceptionOnEmptyCSSLocator(){
        $this->object = new CCSSLocator();
    } 
    
    /**
     * @expectedException CException
     * @expectedExceptionMessage Css selector must be defined
     */
    public function testExceptionOnNullCSSLocator(){
        $this->object = new CCSSLocator(null);
    }
    
    public function testSetAndGetCssSelector(){
        $this->object = new CCSSLocator($this->testSelector);
        $this->assertEquals($this->testSelector,$this->object->getDocumentLocator());
    }

}

?>
