<?php

/**
 * Test class for CWebSource.
 * Generated by PHPUnit on 2011-02-01 at 21:37:40.
 */
class CXPathLocatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CCSSLocator
     */
    protected $object;


    /**
     * @expectedException CException
     * @expectedExceptionMessage Xpath query must be defined
     */
    public function testExceptionOnNullXPathLocator() {
        $this->object = new CXPathLocator(null);
    }

    public function testSetAndGetXPathLocator() {
        $this->object = new CXPathLocator('/html/body/div/a');
        $this->assertEquals('/html/body/div/a', $this->object->getDocumentLocator());
    }

}

?>
